services:
  tomographic_map_matching:
    build: .
    network_mode: host
    environment:
      - DISPLAY
      - TERM
    volumes:
      - /dev/dri:/dev/dri
      - /etc/localtime:/etc/localtime:ro
      - /data/$USER/workspace/tomographic-map-matching/tomographic-map-matching:/home/user/tomographic-map-matching
      - /data/$USER/slicematch-research/varied-height:/data:ro
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
