misc:
  gpu_mode: True
  mode: val

model:
  pretrain: '/weights/model_3dmatch.pth'
  transformer_architecture: ['self', 'cross', 'self', 'cross', 'self', 'cross']
  with_cross_pos_embed: True

data:
  benchmark: 3DMatch
  max_pts: 50000

coarse_matching:
  matching_radius: 0.05
  num_gt_coarse_corr: 128
  num_est_coarse_corr: 256
  coarse_overlap_threshold: 0.1

fine_matching:
  point_per_patch: 64
  fine_matching_topk: 3
  fine_matching_mutual: True
  fine_matching_confidence_threshold: 0.05
  fine_matching_use_dustbin: False
  fine_matching_use_global_score: False
  fine_matching_correspondence_threshold: 3
